dwitter/urls.py
from django.urls import (
    path,
    include,
)
from .views import (
    dashboard,
    profile_list,
    profile,
    image_request,
    ImageListView,
    ImageDetailView,
    ImageDeleteView,
)

app_name = "dwitter"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("profile_list", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    path('add_pic', image_request, name = "image_add"),
    path('gellery/<int:pk>', ImageListView.as_view(), name = "image_all"),
    path("image_detail/<int:pk>", ImageDetailView.as_view(), name="image_detail"),
    path("image_delete/<int:pk>", ImageDeleteView.as_view(), name="image_delete"),
]

social/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)
from django.conf import settings  
from django.conf.urls.static import static  


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('dwitter.urls')),
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import (
    path,
    include,
)
from .views import *

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", register, name="register"),
]

dwitter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.add(instance.profile)
        user_profile.save()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )

    def __str__(self):
        return self.user.username
    
class Dweet(models.Model):
    user = models.ForeignKey(
        User, related_name="dweets", on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )
  
class UploadImage(models.Model):  
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=False, related_name="images")
    caption = models.CharField(max_length=200, blank=True)  
    image = models.ImageField(upload_to='images', blank=False)  
  
    def __str__(self):  
        return (
            f"{self.caption}, "
            f"{self.profile}"
        )

users/models.py
from django.db import models

# Create your models here.

dwitter/forms.py
from typing import Any
from django import forms
from .models import (
    Dweet,
    UploadImage,
)

class DweetForm(forms.ModelForm):
    body = forms.CharField(required=True)
    widget=forms.widgets.Textarea(
        attrs={
            "placeholder": "Dweet something...",
            "class": "textarea is-success is-medium",
        }
    ),
    label="",

    class Meta:
        model = Dweet
        exclude = ("user", )
  
class UserImageForm(forms.ModelForm):  
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')  
        super(UserImageForm, self).__init__(*args, **kwargs)

    class Meta: 
        model = UploadImage  
        exclude = ("profile", )


    def save(self, commit: bool = True) -> Any:
        instance = super(UserImageForm, self).save(commit=False)
        instance.profile = self.user.profile
        if commit:
            instance.save()
        return instance

users/forms.py
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

dwitter/views.py
from typing import Any
from django.db import models
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
)
from .models import (
    Profile,
    Dweet,
    UploadImage,
)
from .forms import (
    DweetForm,
    UserImageForm,
)


def dashboard(request):
    if request.user.is_authenticated:
        form = DweetForm(request.POST or None)
        if request.method == "POST":
            if form.is_valid():
                dweet = form.save(commit=False)
                dweet.user = request.user
                dweet.save()
                return redirect("dwitter:dashboard")
            
        followed_dweets = Dweet.objects.filter(
            user__profile__in=request.user.profile.follows.all()
        ).order_by("-created_at")

        return render(
            request,
            "dwitter/dashboard.html",
            {"form": form, "dweets": followed_dweets},
        )
    else:
        return redirect("login")

def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "dwitter/profile_list.html", {"profiles": profiles})

def profile(request, pk):
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request, "dwitter/profile.html", {"profile": profile})

def image_request(request):  
    if request.method == 'POST': 
        form = UserImageForm(request.POST, request.FILES, user=request.user)  
        if form.is_valid():  
            uploadimage = form.save(commit=False)
            uploadimage.profile = request.user.profile
            uploadimage.save()   
            img_object = form.instance                
            return render(request, 'image_form.html', {'form': form, 'img_obj': img_object}) 
    else:  
        form = UserImageForm(user=request.user)  
  
    return render(request, 'image_form.html', {'form': form})

class ImageListView(ListView):
    model = UploadImage
    template_name = "image/image_list.html"
    context_object_name = "my_images"

    def get_queryset(self):
        queryset = UploadImage.objects.filter(profile=self.kwargs["pk"])
        return queryset

class ImageDetailView(DetailView):
    model = UploadImage
    template_name = "image/image_detail.html"
    context_object_name = "my_image"

    def get_queryset(self):
        queryset = UploadImage.objects.all().filter(pk=self.kwargs["pk"])   
        return queryset

class ImageDeleteView(LoginRequiredMixin, DeleteView):
    model = UploadImage
    context_object_name = "my_image"
    template_name = "image/image_confirm_delete.html"
    success_url = reverse_lazy("dwitter:dashboard")

users/views.py
from django.contrib.auth import login
from django.shortcuts import (
    redirect, 
    render,
)
from django.urls import reverse
from .forms import (
    CustomUserCreationForm,
)

def register(request):
    if request.method == "GET":
        return render(
            request, "users/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(reverse("dwitter:dashboard"))

dwitter/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"> 
    <title>Dwitter</title>
</head>
<body>
    <a href="{% url 'dwitter:dashboard' %} ">
    <section class="hero is-small is-success mb-4">
        <div class="hero-body">
            <h1 class="title is-1">Dwitter</h1>
            <p class="subtitle is-4">
                Your tiny social network built with Django
            </p>
            <p>
                Hello, {{ user.username|default:'Guest' }}!
            </p>
            <div>
                {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}">Logout</a>
                    <a href="{% url 'password_change' %}">Change password</a>
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </section>
    </a>

    <div class="container">
        <div class="columns">

            {% block content %}

            {% endblock content %}

        </div>
    </div>
</body>
</html>

dwitter/templates/dwitter/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    {% for followed in user.profile.follows.all %}
        {% for dweet in dweets %}
        <div class="box">
            {{dweet.body}}
            <span class="is-small has-text-grey-light">
                ({{ dweet.created_at }} by {{ dweet.user.username }})
            </span>
        </div>
        {% endfor %}
    {% endfor %}
</div>

<div class="column is-one-third">
    <div class="block">
        <a href="{% url 'dwitter:profile_list' %} ">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <a href="{% url 'dwitter:profile' request.user.profile.id %} ">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>
    <div class="block">
        <div class="block">
            <h2 class="title is-2">Add a Dweet</p>
        </div>
        <div class="block">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button is-success is-fullwidth is-medium mt-5"
                        type="submit">Dweet
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

dwitter/templates/dwitter/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

    <div class="block">
        <div>
            <div style="float:left">
                <h1 class="title is-1">
                {{profile.user.username|upper}}'s Dweets
                </h1>
            </div>
            <div style="float:right">
                <a href="{% url 'dwitter:image_all' pk=profile.pk %}">
                    <button class="button is-dark is-outlined is-fullwidth">
                        Photo
                    </button>
                </a>
            </div>
        </div>
    
            
    <form method="post">
        {% csrf_token %}
        <div class="buttons has-addons" style="padding-left:10px">
        {% if profile in user.profile.follows.all %}
            <button class="button is-success is-static">
                Follow
            </button>
            <button class="button is-danger"
                    name="follow"
                    value="unfollow">
                Unfollow
            </button>
        {% else %}
            <button class="button is-success"
                    name="follow"
                    value="follow">
                Follow
            </button>
            <button class="button is-danger is-static">
                Unfollow
            </button>
        {% endif %}
        </div>
    </form>
    </div>

    <div class="content">
        {% for dweet in profile.user.dweets.all %}
            <div class="box">
                {{ dweet.body }}
                <span class="is-small has-text-grey-light">
                    ({{ dweet.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>

</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'dwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
        <a href="{% url 'dwitter:image_add' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                Add Image
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'dwitter:profile' following.id %} ">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'dwitter:profile' follower.id %} ">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

dwitter/templates/dwitter/profile_list.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
      <div class="card">
        <a href="{% url 'dwitter:profile' profile.id %}">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <img src="https://bulma.io/images/placeholders/96x96.png"
                       alt="Placeholder image">
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4">
                  {{ profile.user.username }}
                </p>
                <p class="subtitle is-6">
                  @{{ profile.user.username|lower }}
                </p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

{% endfor %}

</div>

{% endblock content %}

dwitter/templates/image/image_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete this image?</p>
    <img src="{{ my_image.image.url }}" alt="connect" style="max-height:100px">
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

dwitter/templates/image/image_detail.html
{% extends "base.html" %}
{% block content %}
<div class="block">
    <div>
        <h2>{{ my_image.caption }}</h2>
        {% if my_image.profile == user.profile %}
        <a href="{% url 'dwitter:image_delete' my_image.pk %}">Delete photo</a>
        {% endif %}
    </div>
    <div>
        <img src="{{ my_image.image.url }}" alt="connect">
    </div>
</div>
    
{% endblock %}

dwitter/templates/image/image_list.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

    <div class="block">
    <h1 class="title is-1">Photos</h1>
    <div class="content" style="max-width: 30%;">
        {% if my_images %}
            {% for image in my_images %}
                <div class="box">
                    <a href="{% url 'dwitter:image_detail' image.pk %}"><h4>{{ image.caption }}</h4></a>
                    <img src="{{ image.image.url }}" alt="connect" style="max-height:100px">  
                </div>
            {% endfor %}
        {% else %}
            <div><h3>No images</h3></div>
        {% endif %}
    </div>
    </div>
</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'dwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
        <a href="{% url 'dwitter:image_add' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                Add Image
            </button>
        </a>
    </div>
</div>

{% endblock content %}

dwitter/templates/image_form.html
{% extends 'base.html' %}  
  
{% block content %}  
    <form method="post" enctype="multipart/form-data">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <button type="submit">Upload</button>  
    </form>  
  
    {% if img_obj %}  
        <h3>Succesfully uploaded : {{img_obj.caption}}</h3>  
        <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">  
    {% endif %}  
    <div class="column is-one-third">
    
        <div class="block">
            <a href="{% url 'dwitter:profile' request.user.profile.id %} ">
                <button class="button is-success is-light is-outlined is-fullwidth">
                    My Profile
                </button>
            </a>
            <a href="{% url 'dwitter:image_all' request.user.profile.id %}">
                <button class="button is-dark is-outlined is-fullwidth">
                    My Gallery
                </button>
            </a>
        </div>
    </div>
  
{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<h2>Register</h2>

<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Register">
</form>

<a href="{% url 'login' %}">Back to login</a>
{% endblock %}